function Hd = lowpass_filter
%LOWPASS_FILTER Generates coefficients for the lowpass filter portion of
%the receiver front end.

% Authors: (ECE 486 Group 8, Spring 2018)
%   Christian Auspland, Matt Blanchard, Ben Grooms

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 25-Mar-2018 15:38:52

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values arein Hz.
Fs = 50000;      % Sampling Frequency

Fpass = 1500;    % Passband Frequency
Fstop = 24500;   % Stopband Frequency
Apass = 0.5;     % Passband Ripple (dB)
Astop = 65;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

for i = 1 : ceil(size(Hd.sosMatrix, 1))
    coeff((5*i - 4) : 5*i)= Hd.sosMatrix(i, [1:3,5:6]);
end
    
csvwrite('lowpass_coeff.csv', coeff);

% [EOF]
