/*
 * @file
 * @brief Test program to illustrate the use of the ECE 486 lab 1 task 2
 * @author ECE486 Lab Group 8
 * @author Christian Auspland
 * @author Matthew Blanchard
 * @author Ben Grooms
 *
 * @date Feb 19, 2018
 */

#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"

#include "ece486.h"
#include "running_mean.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

extern FlagStatus KeyPressed;   // Use to detect button presses

int main(void)
{
  int nsamp;
  float *input, *output1;

  int M = 24;
  struct calc_data *s;

  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   * 
   * If your discovery board has been modified to support the external 
   * HSE reference, use the (better quality crystal controlled) HSE 
   * configuration.  If not, you can use the MSI reference, and things 
   * should still work -- but your clocks will drift over time.
   * 
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   * 
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  initialize_ece486(FS_48K, MONO_IN, STEREO_OUT, MSI_INTERNAL_RC);
  //initialize_ece486(FS_50K, MONO_IN, STEREO_OUT, HSE_EXTERNAL_8MHz);
  //initialize(FS_48K, MONO_IN, MONO_OUT);


  /*
   * Allocate Required Memory
   */
  nsamp = getblocksize();
	
  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);
  
  if (input==NULL || output1==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }
  
  /*
   * Normally we avoid printf()... especially once we start actually 
   * processing streaming samples.  This is here to illustrate the 
   * use of printf for debugging programs.
   * 
   * To see the printf output, connect to the ST-Link serial port.
   * Use: 115200 8N1
   */
  printf("Starting execution using %d samples per input block.\n",nsamp);
  
  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */

  s = init_running_mean(M,nsamp);
  

  while(1){
    /*
     * Ask for a block of ADC samples to be put into the working buffer
     *   getblock() will wait here until the input buffer is filled...  On return
     *   we work on the new data buffer... then return here to wait for 
     *   the next block
     */
    getblock(input);	

    /*
     * signal processing code to calculate the required output buffers
     */ 
 
    DIGITAL_IO_SET(); 	// Use a scope on PD0 to measure execution time
    
    calc_running_mean(input, output1, s);

    DIGITAL_IO_RESET();	// (falling edge....  done processing data )
    
    /*
     * pass the processed working buffer back for DAC output
     */
    putblockstereo(output1,input);
    
    /*
    if (KeyPressed) {
	    printf("block size: %d\n",nsamp);
      KeyPressed = RESET;
          
     //BSP_LCD_GLASS_DisplayString( (uint8_t *)lcd_str);
    //  BSP_LED_Toggle(LED5);
    }
    */
  }
}
