/*
 * @file filter_real.c
 * @brief Test program to illustrate the real time use of the ECE 486 lab 3 task 2 filter
 * @author ECE486 Lab Group 8
 * @author Christian Auspland
 * @author Matthew Blanchard
 * @author Ben Grooms
 *
 * @date Mar 19, 2018
 */

#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"

#include "ece486.h"
#include "ece486_biquad.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#define PI 3.14159265

extern FlagStatus KeyPressed;   // Use to detect button presses

int main(void)
{
  int nsamp;
  float *input, *output1;

  static float biquad_coefs[] = {
    0.0212,0.035867,0.018292,0.02907,0.45505,
    1,1.1844,0.9801,-0.31977,0.68808,
    1,-1.7733,0.88106,-0.80814,0.7612,
    1,-1.5756,0.92568,-1.157,0.92362,
    1,-0.52907,0.7325,0.29651,0.9874
   };

  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   *
   * If your discovery board has been modified to support the external
   * HSE reference, use the (better quality crystal controlled) HSE
   * configuration.  If not, you can use the MSI reference, and things
   * should still work -- but your clocks will drift over time.
   *
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   *
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  //initialize_ece486(FS_48K, MONO_IN, STEREO_OUT, MSI_INTERNAL_RC);
  initialize_ece486(FS_50K, MONO_IN, STEREO_OUT, MSI_INTERNAL_RC);


  /*
   * Allocate Required Memory
   */
  nsamp = getblocksize();

  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);

  if (input==NULL || output1==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }

  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */

  BIQUAD_T *filter_test = init_biquad(5, 1, biquad_coefs, nsamp);


  while(1){
    /*
     * Ask for a block of ADC samples to be put into the working buffer
     *   getblock() will wait here until the input buffer is filled...  On return
     *   we work on the new data buffer... then return here to wait for
     *   the next block
     */
    getblock(input);

    /*
     * signal processing code to calculate the required output buffers
     */

    DIGITAL_IO_SET(); 	// Use a scope on PD0 to measure execution time

    calc_biquad(filter_test, input, output1);

    DIGITAL_IO_RESET();	// (falling edge....  done processing data )

    /*
     * pass the processed working buffer back for DAC output
     */
    putblockstereo(output1,input);

  }
  destroy_biquad(filter_test); 

}
